### ISSUE TITLE
Sec type `2` unsupported? Auth with password fails..

### ISSUE THREAD

**Issue by goodboy** [barneygale/asyncvnc#1]
```python
Traceback (most recent call last):
  File "/home/goodboy/repos/piker/snippets/async_vnc.py", line 21, in <module>
    asyncio.run(run_client())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/goodboy/repos/piker/snippets/async_vnc.py", line 5, in run_client
    async with asyncvnc.connect(
  File "/usr/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/home/goodboy/repos/piker/310/lib/python3.10/site-packages/asyncvnc.py", line 501, in connect
    client = await Client.create(reader, writer, username, password)
  File "/home/goodboy/repos/piker/310/lib/python3.10/site-packages/asyncvnc.py", line 420, in create
    raise ValueError(f'unsupported security types: {security_types}')
ValueError: unsupported security types: {2}
```

Is there a way to know what each sec type maps to and how you must change your server config to make the connection work?

**Comment by barneygale** [comment]
Silly error on my part - try upgrading to asyncvnc 1.1.0?

**Comment by goodboy** [comment]
I'm actually on master, will pull and test shortly 🏄🏼

**Comment by goodboy** [comment]
Yup that fixed it I think 👍🏼 

@barneygale would you take some tests that use `x11vnc` to test against an actual implementation - like full system type tests?

**Comment by barneygale** [comment]
:o that would be amazing!

**Comment by goodboy** [comment]
yeah i'm thinking we could make this client pretty robust with that.

my main use case is driving gui apps inside containers that i don't want to deal with native, so maybe a little docker err sumthing could work here too?

I've done end-to-end tests like that before and they usually serve in getting things pretty correct 🏄🏼

**Comment by goodboy** [comment]
Ok so I think the first issue is solved but now auth isn't working correctly?

`x11vnc -display :0 -noipv6 -forever -noxdamage -ncache_cr  -passwd doggy`

Run the std connect block with `password='doggy'` gets:

```python
 File "/home/goodboy/repos/piker/snippets/async_vnc.py", line 25, in asyncvnc_main
    asyncio.run(run_client())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/goodboy/repos/piker/snippets/async_vnc.py", line 8, in run_client
    async with asyncvnc.connect(
  File "/usr/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/home/goodboy/repos/asyncvnc/asyncvnc.py", line 566, in connect
    client = await Client.create(reader, writer, username, password, host_key)
  File "/home/goodboy/repos/asyncvnc/asyncvnc.py", line 519, in create
    raise PermissionError('Auth failed')
PermissionError: Auth failed
```

Not sure what's up, but if i remove the `-passwd` line it works.

**Comment by goodboy** [comment]
@barneygale see the test suite in #4 that demonstrates the auth failing.

**Comment by barneygale** [comment]
Try the latest main, please?
